name: Build, Test, Format, Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format repo
        run: pnpm exec prettier --check .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint repo
        run: pnpm exec eslint .

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build method
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.7.1

      - name: Test method
        run: pnpm test
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
